// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-d9bKzLkDylQiOT5_ZsqbejsB-nfmjBE',
    appId: '1:33491188906:web:1793b610944f774dc6e4d3',
    messagingSenderId: '33491188906',
    projectId: 'app-event-calendar',
    authDomain: 'app-event-calendar.firebaseapp.com',
    storageBucket: 'app-event-calendar.firebasestorage.app',
    measurementId: 'G-NSKYWMS7TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLORajkeC3JlsVzZFhWr_fqmDJRZPs2Lc',
    appId: '1:33491188906:android:e939d3abd6b679c9c6e4d3',
    messagingSenderId: '33491188906',
    projectId: 'app-event-calendar',
    storageBucket: 'app-event-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvfr4i7aFe_Eaf1g6Ft3NDz8lFqgdsFQ',
    appId: '1:33491188906:ios:55734018aa3e2614c6e4d3',
    messagingSenderId: '33491188906',
    projectId: 'app-event-calendar',
    storageBucket: 'app-event-calendar.firebasestorage.app',
    iosBundleId: 'com.example.gajananMaharajSevekariAppDemo',
  );
}
