# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store Production Track"
  lane :deploy_production do |options|
    target_build = options[:build_number]
    UI.message("🚀 Preparing to upload build #{target_build} to Production")

    upload_to_play_store(
      track: 'production',
      package_name: 'com.gajanan.maharaj.sevekari',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: false,
      skip_upload_images: false,
      release_status: 'completed'
    )
    UI.success("🎉 Successfully uploaded build #{target_build} to Production!")
  end

  desc "Deploy a new version to a specific track (beta/internal)"
  lane :deploy_closed_testing do |options|
    target_build = options[:build_number]
    target_track = options[:track] || 'alpha'

    UI.message("🚀 Preparing to upload build #{target_build} to #{target_track} track")

    upload_to_play_store(
      track: target_track,
      package_name: 'com.gajanan.maharaj.sevekari',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: false,
      skip_upload_images: false,
      release_status: 'completed'
    )

    UI.success("🎉 Successfully uploaded build #{target_build} to the #{target_track} track!")
  end
end
